#!/usr/bin/env python3
"""
agents/agent_factory_agent.py — AgentFactory: Self-Expanding Agent Creator
Analyzes what MaxAI needs, auto-generates new specialized agents.
This makes MaxAI self-expanding — always adds agents as the company grows.
"""
import json, logging, os, time
from pathlib import Path
from datetime import datetime

log = logging.getLogger("agents.agent_factory")
BASE = Path("/root/my_personal_ai")
BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "8428552836:AAHRCJZf3G30LSe8vuXpVTwr_mPrzVJVIWM")
CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID", "1985320458")
FACTORY_LOG = BASE / "data" / "agent_factory_log.json"

try:
    from agents.base_agent import BaseAgent, AgentInfo
    HAS_BASE = True
except ImportError:
    BaseAgent = object
    AgentInfo = None
    HAS_BASE = False

AGENT_WISHLIST = [
    {"name": "instagram_parser_agent", "class": "InstagramParserAgent",
     "desc": "Parses Instagram business profiles for B2B leads", "priority": 1},
    {"name": "avito_scanner_agent", "class": "AvitoScannerAgent",
     "desc": "Scans Avito for businesses that need automation", "priority": 1},
    {"name": "client_onboarding_agent", "class": "ClientOnboardingAgent",
     "desc": "Automates new client onboarding flow: welcome, brief, kickoff", "priority": 1},
    {"name": "invoice_generator_agent", "class": "InvoiceGeneratorAgent",
     "desc": "Auto-generates invoices for completed MaxAI projects", "priority": 2},
    {"name": "competitor_tracker_agent", "class": "CompetitorTrackerAgent",
     "desc": "Tracks kwork.ru competitors, adjusts pricing automatically", "priority": 2},
    {"name": "portfolio_showcase_agent", "class": "PortfolioShowcaseAgent",
     "desc": "Publishes completed work to portfolio channels daily", "priority": 2},
    {"name": "telegram_ads_agent", "class": "TelegramAdsAgent",
     "desc": "Manages Telegram ad placements in relevant channels", "priority": 3},
    {"name": "seo_optimizer_agent", "class": "SeoOptimizerAgent",
     "desc": "Optimizes content for Yandex/Google SEO", "priority": 3},
    {"name": "upsell_agent", "class": "UpsellAgent",
     "desc": "Identifies upsell opportunities with existing clients", "priority": 2},
    {"name": "referral_agent", "class": "ReferralAgent",
     "desc": "Manages referral program — reward clients who refer others", "priority": 3},
]

AGENT_STUB = """\
#!/usr/bin/env python3
\"\"\"
agents/{filename}.py
{description}
Auto-generated by AgentFactory — {created_at}
\"\"\"
import json, logging, os, time
from pathlib import Path
from datetime import datetime

log = logging.getLogger("agents.{logname}")
BASE = Path("/root/my_personal_ai")
BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "8428552836:AAHRCJZf3G30LSe8vuXpVTwr_mPrzVJVIWM")
CHAT_ID   = os.environ.get("TELEGRAM_CHAT_ID", "1985320458")
DATA_FILE = BASE / "data" / "{filename}_state.json"

try:
    from agents.base_agent import BaseAgent, AgentInfo
    HAS_BASE = True
except ImportError:
    BaseAgent = object; AgentInfo = None; HAS_BASE = False


class {classname}(BaseAgent if HAS_BASE else object):
    name = "{logname}"
    VERSION = "1.0-autogenerated"

    def __init__(self, **kwargs):
        if HAS_BASE:
            super().__init__("{logname}")

    def can_handle(self, text: str) -> bool:
        return "{logname}" in text.lower()

    def info(self):
        if AgentInfo:
            return AgentInfo(name="{logname}", description="{description}",
                           capabilities=["execute", "report"])
        return None

    def _tg(self, text):
        try:
            import urllib.request as ur
            data = json.dumps({{"chat_id": CHAT_ID, "text": text}}).encode()
            req = ur.Request(f"https://api.telegram.org/bot{{BOT_TOKEN}}/sendMessage",
                            data=data, headers={{"Content-Type": "application/json"}})
            ur.urlopen(req, timeout=8)
        except Exception:
            pass

    def execute(self):
        \"\"\"Main logic — implement specific automation here.\"\"\"
        state = json.loads(DATA_FILE.read_text()) if DATA_FILE.exists() else {{"runs": 0}}
        state["runs"] = state.get("runs", 0) + 1
        state["last_run"] = datetime.now().isoformat()
        DATA_FILE.write_text(json.dumps(state, ensure_ascii=False))
        run_count = state.get('runs', 0)
        result = f"Action completed run #{run_count}: {description}"
        self._tg(result)
        return result

    def process(self, text: str = "", source: str = "internal", **kwargs) -> str:
        return self.execute()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print({classname}().execute())
"""


class AgentFactoryAgent(BaseAgent if HAS_BASE else object):
    name = "agent_factory"

    def __init__(self, **kwargs):
        if HAS_BASE:
            super().__init__("agent_factory")

    def can_handle(self, text: str) -> bool:
        return any(k in text.lower() for k in ["factory", "create agent", "новый агент", "добавить агента"])

    def info(self):
        if AgentInfo:
            return AgentInfo(
                name="agent_factory",
                description="Creates new specialized agents autonomously as MaxAI grows",
                capabilities=["create_agent", "deploy_agent", "audit_needs", "agent_wishlist"]
            )
        return None

    def _tg(self, text):
        try:
            import urllib.request as ur
            data = json.dumps({"chat_id": CHAT_ID, "text": text}).encode()
            req = ur.Request(
                f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
                data=data, headers={"Content-Type": "application/json"}
            )
            ur.urlopen(req, timeout=8)
        except Exception:
            pass

    def get_created_names(self):
        if FACTORY_LOG.exists():
            try:
                return {item["name"] for item in json.loads(FACTORY_LOG.read_text())}
            except Exception:
                pass
        return set()

    def create_next_agent(self):
        created = self.get_created_names()
        next_agent = None

        for agent in sorted(AGENT_WISHLIST, key=lambda x: x["priority"]):
            if agent["name"] not in created:
                path = BASE / "agents" / f"{agent['name']}.py"
                if not path.exists():
                    next_agent = agent
                    break

        if not next_agent:
            return "All planned agents already deployed!"

        logname = next_agent["name"].replace("_agent", "").replace("_", "_")
        code = (AGENT_STUB
            .replace("TMPL_FILENAME", next_agent["name"])
            .replace("TMPL_CLASSNAME", next_agent["class"])
            .replace("TMPL_DESCRIPTION", next_agent["desc"])
            .replace("TMPL_LOGNAME", logname)
            .replace("TMPL_CREATED", datetime.now().strftime("%Y-%m-%d %H:%M"))
        )

        path = BASE / "agents" / f"{next_agent['name']}.py"
        path.write_text(code)

        # Log
        history = json.loads(FACTORY_LOG.read_text()) if FACTORY_LOG.exists() else []
        history.append({
            "name": next_agent["name"],
            "class": next_agent["class"],
            "created": datetime.now().isoformat(),
            "priority": next_agent["priority"],
        })
        FACTORY_LOG.write_text(json.dumps(history, ensure_ascii=False))

        remaining = sum(1 for a in AGENT_WISHLIST
                        if a["name"] not in created and a["name"] != next_agent["name"])
        msg = (f"🏭 AgentFactory: Created {next_agent['class']}!\n"
               f"📁 {next_agent['name']}.py\n"
               f"🎯 {next_agent['desc']}\n"
               f"📋 {remaining} more in wishlist")
        self._tg(msg)
        return f"Created {next_agent['class']}! ({remaining} more pending)"

    def process(self, text: str = "", source: str = "internal", **kwargs) -> str:
        return self.create_next_agent()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print(AgentFactoryAgent().create_next_agent())

# Alias for backward compatibility
AgentFactory = AgentFactoryAgent
