#!/usr/bin/env python3
"""
credential_vault.py — MaxAI Central Credential Vault
Централизованное управление всеми ключами и паролями.
Автоматически инжектирует credentials во все агенты и конфиги.
"""
import json, logging, os, subprocess, sys
from pathlib import Path

LOG_DIR = Path('/root/my_personal_ai/logs')
LOG_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[logging.StreamHandler(), logging.FileHandler(str(LOG_DIR / 'vault.log'))]
)
log = logging.getLogger('vault')

# ─── Master credentials ─────────────────────────────────────────────────────
VAULT = {
    # Bybit Trading Bot API
    'BYBIT_API_KEY':    'O8NZsb1QOlQET3c3kH',
    'BYBIT_API_SECRET': 'Nt5ZdXPNrJvGQQg6DMeBkcDtdRpMhEybhHHQ',

    # Bybit Personal AI API
    'BYBIT_PA_API_KEY':    '3sXf9hXwbhxOtp2Ux0',
    'BYBIT_PA_API_SECRET': 'arsNvYHxGR7k5hKF8aONWDJA17klvsxuWBMr',

    # Telegram
    'TELEGRAM_BOT_TOKEN': '8428552836:AAHRCJZf3G30LSe8vuXpVTwr_mPrzVJVIWM',
    'TELEGRAM_CHAT_ID':   '1985320458',

    # Bybit Account
    'BYBIT_EMAIL':    'jimmorrisoninlove@gmail.com',
    'BYBIT_PASSWORD': 'Fukcyoubithc48',

    # Kwork
    'KWORK_EMAIL':    'jimmorrisoninlove@gmail.com',
    'KWORK_PASSWORD': 'Fukcyoubithc48',

    # Email
    'EMAIL_FROGGY': 'froggyinternet@gmail.com',
    'EMAIL_FROGGY_PASS': 'umtp ewnj biih wfbp',  # App password
    'EMAIL_JIM':    'jimmorrisoninlove@gmail.com',
    'EMAIL_JIM_PASS': 'Fukcyoubithc48',

    # Crypto wallet
    'TRC20_WALLET': 'TAN8FijYFgmM8wCq8Y5jogkry9kPaY9NE2',

    # PostgreSQL
    'POSTGRES_USER': 'postgres',
    'POSTGRES_PASS': 'hyperion_v12_pass',
    'POSTGRES_DB':   'hyperion',
    'POSTGRES_URL':  'postgresql://postgres:hyperion_v12_pass@localhost/hyperion',

    # Trading mode flags (CRITICAL - do not remove)
    'TRADING_LIVE_CONFIRMED': 'true',
    'BYBIT_TESTNET': 'false',

    # Server
    'VPS_IP':   '77.90.2.171',
    'VPS_USER': 'root',
    'VPS_PASS': 'cpySlIutZ5Ef0mRsfWXh',
}

# ─── Target .env files to update ────────────────────────────────────────────
ENV_TARGETS = [
    '/root/my_personal_ai/.env',
    '/root/bybit-bot/.env',
]

# ─── Systemd environment files ──────────────────────────────────────────────
SYSTEMD_ENV_TARGETS = [
    '/etc/systemd/system/bybit-monitor.service',
    '/etc/systemd/system/personal-ai.service',
    '/etc/systemd/system/maxai-guardian.service',
    '/etc/systemd/system/maxai-tgbot.service',
]

def write_env_file(path: str):
    """Write .env file with all credentials."""
    content_lines = [
        '# MaxAI Master Environment — auto-generated by credential_vault.py',
        f'# Updated: {__import__("datetime").datetime.utcnow().isoformat()}',
        '',
    ]
    for key, val in VAULT.items():
        content_lines.append(f'{key}={val}')

    Path(path).parent.mkdir(exist_ok=True)
    Path(path).write_text('\n'.join(content_lines) + '\n')
    log.info('Written .env: %s', path)


def inject_into_systemd(service_file: str):
    """Inject Environment= lines into systemd service file."""
    path = Path(service_file)
    if not path.exists():
        log.warning('Service file not found: %s', service_file)
        return

    content = path.read_text()

    # Key envvars to inject
    INJECT = {
        'BYBIT_API_KEY': VAULT['BYBIT_API_KEY'],
        'BYBIT_API_SECRET': VAULT['BYBIT_API_SECRET'],
        'TELEGRAM_BOT_TOKEN': VAULT['TELEGRAM_BOT_TOKEN'],
        'TELEGRAM_CHAT_ID': VAULT['TELEGRAM_CHAT_ID'],
        'KWORK_EMAIL': VAULT['KWORK_EMAIL'],
        'KWORK_PASSWORD': VAULT['KWORK_PASSWORD'],
        'POSTGRES_URL': VAULT['POSTGRES_URL'],
    }

    env_lines = '\n'.join(f'Environment="{k}={v}"' for k, v in INJECT.items())

    # Check if already has EnvironmentFile or Environment
    if 'EnvironmentFile=' in content:
        log.info('Service %s already has EnvironmentFile=', service_file)
        return

    # Add after [Service] section
    if '[Service]' in content:
        new_content = content.replace('[Service]', f'[Service]\nEnvironmentFile=-/root/my_personal_ai/.env', 1)
        path.write_text(new_content)
        log.info('Injected EnvironmentFile into %s', service_file)


def check_agent_credentials():
    """Verify agents have access to credentials."""
    agents_dir = Path('/root/my_personal_ai/agents')
    issues = []

    for agent in agents_dir.glob('*.py'):
        content = agent.read_text(errors='ignore')
        # Check if hardcoded or uses env
        if 'os.environ' not in content and 'BYBIT_API_KEY' in content:
            # Uses hardcoded key — that's fine for now
            pass

    return issues


def create_master_env():
    """Create the master environment file that all services load."""
    env_path = '/root/my_personal_ai/.env'
    write_env_file(env_path)

    # Also write to bybit-bot
    write_env_file('/root/bybit-bot/.env')

    # Create a shell-sourceable version
    shell_env = '/root/maxai_env.sh'
    lines = ['#!/bin/bash', '# MaxAI Master Environment — source this file', '']
    for key, val in VAULT.items():
        lines.append(f'export {key}="{val}"')
    Path(shell_env).write_text('\n'.join(lines) + '\n')
    os.chmod(shell_env, 0o600)
    log.info('Written shell env: %s', shell_env)


def run():
    log.info('=== Credential Vault ===')
    create_master_env()

    # Inject into systemd services
    for svc in SYSTEMD_ENV_TARGETS:
        inject_into_systemd(svc)

    # Reload systemd
    subprocess.run(['systemctl', 'daemon-reload'], capture_output=True)

    issues = check_agent_credentials()
    if issues:
        log.warning('Credential issues: %s', issues)
    else:
        log.info('All agents have credential access.')

    log.info('Vault complete. %d credentials managed.', len(VAULT))
    return VAULT


if __name__ == '__main__':
    run()
